name: Deploy 

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Preparing image
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - name : push and build docker image
      run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project:latest

    - name: Create Azure container environment
      run: az containerapp env create -n group-2-container-env -g  ${{ secrets.RESOURCE_GROUP }} --location francecentral

    - name: Deploy to Azure Container 
      run: az containerapp create\
      --resource-group ${{ secrets.RESOURCE_GROUP }}\
      --name group-2-container\
      --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project:latest\
      --cpu 1\
      --memory 2\
      --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }}\
      --registry-username ${{ secrets.REGISTRY_USERNAME }}\
      --registry-password ${{ secrets.REGISTRY_PASSWORD }}\
      --ingress external\
      --target-port 5000\
      --environment group-2-container-env