name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t adde92-project .

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Push Docker image
      run: |
        docker tag adde92-project ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project

    # docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_USERNAME }} ${{ secrets.REGISTRY_LOGIN_SERVER }}