name: Docker Build and Push Images on Github Action
on:
  push:
    branches:
      - docker #
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/irisapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/irisapp:${{ github.sha }}

      # - name: 'Deploy to Azure Container Instances'
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/irisapp:${{ github.sha }}
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     name: projetgroupe2
      #     location: 'west europe'
      #     ports: 8081

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: efreibigdata
          containerAppName: adde92-gr2-container
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: efreibigdata.azurecr.io/irisapp:${{ github.sha }}
          port: 5000
      # - name: Build docker image
      #   uses: docker build . -t irisapp:0.0.1
      
      # - name: Deploy to Azure Container Apps
      #   run: |
      #   az containerapp create --name adde92-gr2-container --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project --cpu 1 --memory 2 --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --environment gr2-container-env --ingress external --target-port 5000
