name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t adde92-project .

    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{secrets.REGISTRY_PASSWORD}}
        sudo docker tag adde92-project ${{secrets.REGISTRY_LOGIN_SERVER}}/adde92-project
        sudo docker push ${{secrets.REGISTRY_LOGIN_SERVER}}/adde92-project

# AZURE_CREDENTIALS : compte de service pour s'authentifier avec l'API Azure
# REGISTRY_LOGIN_SERVER : lien du serveur de la registry (efreibigdata.azurecr.io)
# REGISTRY_USERNAME : nom d'utilisateur de la registry
# REGISTRY_PASSWORD : mot de passe pour la registry
# RESOURCE_GROUP : groupe de ressources Azure (ADDE92-CTP)