name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_LOGIN_SERVER }}
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project

    - name: Create Azure container environment
      run: az containerapp env create -n gr2-container-env -g  ${{ secrets.RESOURCE_GROUP }} --location francecentral

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create --name adde92-gr2-container --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project --cpu 1 --memory 2 --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --environment gr2-container-env --ingress external --target-port 5000
        