name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  lint-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Install Hadolint
    #   run: |
    #     wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
    #     chmod +x hadolint
    #     sudo mv hadolint /usr/local/bin/
    
    # - name: Lint Dockerfile
    #   run: hadolint Dockerfile
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check dockerfile with hadolint
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile
        if grep -q "warning" hadolint_output.txt; then
          echo "Hadolint found warnings in Dockerfile. Fix the warnings and try again."
          exit 1
        fi

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_LOGIN_SERVER }}
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project

    - name: Create Azure container environment
      run: az containerapp env create -n gr2-container-environnement -g  ${{ secrets.RESOURCE_GROUP }} --location francecentral

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create --name adde92-gr2-container --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/adde92-project --cpu 1 --memory 2 --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --environment gr2-container-environnement --ingress external --target-port 5000 --min-replicas 0 --max-replicas 5 --scale-rule-name autoscaling-rule --scale-rule-type http --scale-rule-http-concurrency 100
